# Generated by Django 4.2.7 on 2023-12-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='My_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=75)),
                ('img', models.ImageField(upload_to='imgs')),
                ('title', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=100)),
                ('info_title', models.CharField(max_length=250)),
                ('birth_date', models.CharField(max_length=75)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('rank', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('info_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='My_skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='My_social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=100)),
                ('img', models.CharField(max_length=50)),
            ],
        ),
    ]
