# Generated by Django 4.2.7 on 2023-12-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='imgs')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('text', models.TextField()),
            ],
        ),
    ]
