# Generated by Django 4.2.7 on 2024-01-03 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_projectimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
