# Generated by Django 4.2.7 on 2024-02-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_delete_projectimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_projects',
            name='category',
            field=models.CharField(max_length=50, verbose_name=(('frontend', 'frontend'), ('backend', 'backend'))),
        ),
    ]
