# Generated by Django 4.2.7 on 2024-02-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_alter_my_projects_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_projects',
            name='category',
            field=models.CharField(choices=[('frontend', 'frontend'), ('backend', 'backend')], max_length=50),
        ),
    ]
